export const LOAD_APPOINTMENTS           = 'LOAD_APPOINTMENTS';
export const CREATE_APPOINTMENT          = 'CREATE_APPOINTMENT';
export const DELETE_APPOINTMENT          = 'DELETE_APPOINTMENT';
export const UPDATE_APPOINTMENT          = 'UPDATE_APPOINTMENT';
export const SHOW_EDIT_APPOINTMENT_MODAL = 'SHOW_EDIT_APPOINTMENT_MODAL';
export const HIDE_EDIT_APPOINTMENT_MODAL = 'HIDE_EDIT_APPOINTMENT_MODAL';
export const SET_ERROR                   = 'SET_ERROR';
